# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true

r:
- 3.6

install:
  - R -e "0" --args --bootstrap-packrat
  - R -e "packrat::restore(restart = FALSE)"

# install linux libraries that some R pkgs depend on, add more as needed
addons:
  apt:
    packages:
      - libudunits2-dev

script:
    # build and install custom library with custom functions
  - R -e "install.packages(c('devtools', 'rmarkdown'))"
  - Rscript -e "devtools::install()"
    # render the main mansucript document into HTML/Word/PDF as specified in the Rmd
    # you may need to edit the path and file name to point to the Rmd file to render
  - R -e "rmarkdown::render('analysis/paper/paper.Rmd')"

# be more tolerant :)
warnings_are_errors: false
