# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: xenial
os: linux
cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true

r:
  - 3.6

before_install:
  - R -e "utils::install.packages(c('bookdown', 'devtools', 'knitr', 'rmarkdown'))"

install:
  - R -e "0" --args --bootstrap-packrat
  - R -e "packrat::restore(restart = FALSE)"

# install linux libraries that some R pkgs depend on, add more as needed
addons:
  apt:
    packages:
      - libudunits2-dev

script:
    # render the main mansucript document into HTML/Word/PDF
  - Rscript -e "rmarkdown::render('analysis/paper/paper.Rmd')"

# be more tolerant :)
warnings_are_errors: false
